/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dato.ClienteDAO;
import Dominio.Cliente;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego Vásquez
 */
public class JFrmMantCliente extends javax.swing.JInternalFrame {

    /**
     */
    public JFrmMantCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTxtNumeroTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTxtNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTxtDpiCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTxtTelefonoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTxtDireccionCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTxtCorreoCliente = new javax.swing.JTextField();
        JBtnAgregar = new javax.swing.JButton();
        JBtnBuscar = new javax.swing.JButton();
        JBtnModificar = new javax.swing.JButton();
        JBtnEliminar = new javax.swing.JButton();
        JBtnAyuda = new javax.swing.JButton();
        JBtnCargarData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCliente = new javax.swing.JTable();

        setClosable(true);
        setTitle("Mantenimiento Clientes");

        jPanel1.setBackground(new java.awt.Color(10, 40, 50));

        jPanel2.setBackground(new java.awt.Color(10, 40, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Número de Tarjeta:");

        jLabel2.setText("Nombre del Cliente:");

        jLabel3.setText("DPI Cliente:");

        jLabel4.setText("Teléfono Cliente:");

        jLabel5.setText("Dirección Cliente:");

        jLabel6.setText("Correo del Cliente:");

        JBtnAgregar.setText("Agregar");
        JBtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAgregarActionPerformed(evt);
            }
        });

        JBtnBuscar.setText("Buscar");
        JBtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnBuscarActionPerformed(evt);
            }
        });

        JBtnModificar.setText("Modificar");
        JBtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnModificarActionPerformed(evt);
            }
        });

        JBtnEliminar.setText("Eliminar");
        JBtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEliminarActionPerformed(evt);
            }
        });

        JBtnAyuda.setText("?");
        JBtnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAyudaActionPerformed(evt);
            }
        });

        JBtnCargarData.setText("Cargar Data");
        JBtnCargarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCargarDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtNumeroTarjeta)
                            .addComponent(JTxtNombreCliente)
                            .addComponent(JTxtDpiCliente)
                            .addComponent(JTxtTelefonoCliente)
                            .addComponent(JTxtDireccionCliente)
                            .addComponent(JTxtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(JBtnCargarData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnAyuda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JBtnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBtnAyuda)
                        .addComponent(JBtnCargarData))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTxtNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTxtDpiCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTxtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTxtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JTxtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBtnAgregar)
                            .addComponent(JBtnBuscar)
                            .addComponent(JBtnModificar)
                            .addComponent(JBtnEliminar))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        JTableCliente.setBackground(new java.awt.Color(51, 51, 51));
        JTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Tarjeta", "Nombre Cliente", "DPI Cliente", "Teléfono Cliente", "Dirección Cliente", "Correo Cliente"
            }
        ));
        jScrollPane1.setViewportView(JTableCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*public JFrmMantCliente() throws SQLException {
        initComponents();
        llenar_tabla();
    }*/
    
    public void llenar_tabla() throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Tarjeta");
        modelo.addColumn("Cliente");
        modelo.addColumn("DPI");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Dirección");
        modelo.addColumn("Correo");
        
        ClienteDAO objClienteDAO = new ClienteDAO();
        List<Cliente> cliente = objClienteDAO.select();
        JTableCliente.setModel(modelo);
        String[] dato = new String[6];
        for (int i = 0; i < cliente.size(); i++) {
            dato[0] = cliente.get(i).getNumeroTarjeta();
            dato[1] = cliente.get(i).getNombreCliente();
            dato[2] = cliente.get(i).getDpiCliente();
            dato[3] = cliente.get(i).getTelefonoCliente();
            dato[4] = cliente.get(i).getDireccionCliente();
            dato[5] = cliente.get(i).getCorreoCliente();
            modelo.addRow(dato);
        }
    }
    private void JBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAgregarActionPerformed
        ClienteDAO objClienteDAO = new ClienteDAO();
        Cliente objCliente = new Cliente();

        objCliente.setNumeroTarjeta(JTxtNumeroTarjeta.getText());
        objCliente.setNombreCliente(JTxtNombreCliente.getText());
        objCliente.setDpiCliente(JTxtDpiCliente.getText());
        objCliente.setTelefonoCliente(JTxtTelefonoCliente.getText());
        objCliente.setDireccionCliente(JTxtDireccionCliente.getText());
        objCliente.setCorreoCliente(JTxtCorreoCliente.getText());
        objCliente.setBonosAcumulados("0");
        objCliente.setRentaAcumulada("0");
        objCliente.setMoraAcumulada("0");

        if (objCliente != null) {
            if (objClienteDAO.insert(objCliente) > 0) {
                JOptionPane.showMessageDialog(null, "¡Registro Exitoso!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Registro No Exitoso", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        try {
            llenar_tabla();
        } catch (SQLException ex) {
            Logger.getLogger(JFrmMantCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtnAgregarActionPerformed

    private void JBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnModificarActionPerformed
        ClienteDAO objClienteDAO = new ClienteDAO();
        Cliente objCliente = new Cliente();

        objCliente.setNumeroTarjeta(JTxtNumeroTarjeta.getText());
        objCliente.setNombreCliente(JTxtNombreCliente.getText());
        objCliente.setDpiCliente(JTxtDpiCliente.getText());
        objCliente.setTelefonoCliente(JTxtTelefonoCliente.getText());
        objCliente.setDireccionCliente(JTxtDireccionCliente.getText());
        objCliente.setCorreoCliente(JTxtCorreoCliente.getText());
        objCliente.setBonosAcumulados("0");
        objCliente.setRentaAcumulada("0");
        objCliente.setMoraAcumulada("0");

        if (objCliente != null) {
            if (objClienteDAO.update(objCliente) > 0) {
                JOptionPane.showMessageDialog(null, "¡Registro Modificado Exitosamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Registro No Modificado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        try {
            llenar_tabla();
        } catch (SQLException ex) {
            Logger.getLogger(JFrmMantCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtnModificarActionPerformed

    private void JBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEliminarActionPerformed
        ClienteDAO objClienteDAO = new ClienteDAO();
        Cliente objCliente = new Cliente();

        objCliente.setNumeroTarjeta(JTxtNumeroTarjeta.getText());
        objCliente.setNombreCliente(JTxtNombreCliente.getText());
        objCliente.setDpiCliente(JTxtDpiCliente.getText());
        objCliente.setTelefonoCliente(JTxtTelefonoCliente.getText());
        objCliente.setDireccionCliente(JTxtDireccionCliente.getText());
        objCliente.setCorreoCliente(JTxtCorreoCliente.getText());
        objCliente.setBonosAcumulados("0");
        objCliente.setRentaAcumulada("0");
        objCliente.setMoraAcumulada("0");

        if (objCliente != null) {
            if (objClienteDAO.delete(objCliente) > 0) {
                JOptionPane.showMessageDialog(null, "¡Registro Eliminado Exitosamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Registro No Eliminado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        try {
            llenar_tabla();
        } catch (SQLException ex) {
            Logger.getLogger(JFrmMantCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtnEliminarActionPerformed

    private void JBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnBuscarActionPerformed
        Cliente objCliente = new Cliente();
        ClienteDAO objClienteDAO = new ClienteDAO();
        objCliente.setNumeroTarjeta(JTxtNumeroTarjeta.getText());

        objCliente = objClienteDAO.query(objCliente);

        if (!objCliente.getNumeroTarjeta().equals("")) {

            JOptionPane.showMessageDialog(null, "¡Registro Buscado Exitosamente!", "Información", JOptionPane.INFORMATION_MESSAGE);
            JTxtNumeroTarjeta.setText(objCliente.getNumeroTarjeta());
            JTxtNombreCliente.setText(objCliente.getNombreCliente());
            JTxtDpiCliente.setText(objCliente.getDpiCliente());
            JTxtTelefonoCliente.setText(objCliente.getTelefonoCliente());
            JTxtDireccionCliente.setText(objCliente.getDireccionCliente());
            JTxtCorreoCliente.setText(objCliente.getCorreoCliente());
        } else {
            JOptionPane.showMessageDialog(null, "Registro Inexistente", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            llenar_tabla();
        } catch (SQLException ex) {
            Logger.getLogger(JFrmMantCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_JBtnBuscarActionPerformed

    private void JBtnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnAyudaActionPerformed

    private void JBtnCargarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCargarDataActionPerformed
        try {
            llenar_tabla();
        } catch (SQLException ex) {
            Logger.getLogger(JFrmMantCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtnCargarDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAgregar;
    private javax.swing.JButton JBtnAyuda;
    private javax.swing.JButton JBtnBuscar;
    private javax.swing.JButton JBtnCargarData;
    private javax.swing.JButton JBtnEliminar;
    private javax.swing.JButton JBtnModificar;
    private javax.swing.JTable JTableCliente;
    private javax.swing.JTextField JTxtCorreoCliente;
    private javax.swing.JTextField JTxtDireccionCliente;
    private javax.swing.JTextField JTxtDpiCliente;
    private javax.swing.JTextField JTxtNombreCliente;
    private javax.swing.JTextField JTxtNumeroTarjeta;
    private javax.swing.JTextField JTxtTelefonoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
